app:
  name: gin-user-service
  env: prod
  port: 8080

server:
  readTimeout: 5s
  writeTimeout: 10s
  ShutDownTimeout: 3s


database:
  host: localhost
  port: 5432
  name: users_db
  username: admin
  password: admin123
  ssl: false